import * as FileSystem from 'expo-file-system';
import * as Sharing from 'expo-sharing';

const APP_NAME = 'Mindful Guardian';

export const generateReportContent = (reportData) => {
  const { type, result } = reportData;
  const date = new Date().toLocaleDateString('en-US', {
    year: 'numeric', month: 'long', day: 'numeric',
  });

  let content = `FAMILY DEVELOPMENT REPORT
${APP_NAME}
Date: ${date}

`;

  if (type === 'parenting') {
    const style = result?.primaryStyle;
    content += `PARENTING STYLE ASSESSMENT
==========================
Primary Style: ${style?.name || 'Unknown'}
Description: ${style?.description || ''}

STRENGTHS:
${style?.strengths?.map((s) => `  • ${s}`).join('\n') || '  No data'}

AREAS TO IMPROVE:
${style?.improvements?.map((s) => `  • ${s}`).join('\n') || '  No data'}

ADVICE:
${style?.advice?.map((a, i) => `  ${i + 1}. ${a}`).join('\n') || '  No data'}

Style Breakdown:
${result?.percentages
  ? Object.entries(result.percentages).map(([k, v]) => `  • ${k}: ${v}%`).join('\n')
  : '  No data'}
`;
  } else if (type === 'personality') {
    const type_ = result?.primaryType;
    content += `CHILD PERSONALITY ASSESSMENT
============================
Personality Type: ${type_?.name || 'Unknown'} ${type_?.emoji || ''}
Description: ${type_?.description || ''}

KEY TRAITS:
${type_?.traits?.map((t) => `  • ${t}`).join('\n') || '  No data'}

${result?.ageGroupId ? `Age Group: ${result.ageGroupId}` : ''}
`;
  } else if (type === 'eq') {
    content += `EMOTIONAL INTELLIGENCE (EQ) ASSESSMENT
=======================================
Total Score: ${result?.totalScore || 0}/${result?.maxTotal || 60}
Level: ${result?.level?.level || 'Unknown'}
Percentage: ${result?.percentage || 0}%

DIMENSION SCORES:
${
  result?.dimensionScores
    ? Object.values(result.dimensionScores)
        .map((d) => `  • ${d.name}: ${d.score}/${d.maxScore} (${d.percentage}%)`)
        .join('\n')
    : '  No data'
}
`;
  } else if (type === 'family') {
    content += `COMPLETE FAMILY REPORT
======================
`;
    const parenting = result?.parenting?.result;
    const personality = result?.personality?.result;
    const eq = result?.eq?.result;

    if (parenting) {
      content += `Parenting Style: ${parenting.primaryStyle?.name || 'Unknown'}\n`;
    }
    if (personality) {
      content += `Child Personality: ${personality.primaryType?.name || 'Unknown'} ${personality.primaryType?.emoji || ''}\n`;
    }
    if (eq) {
      content += `EQ Score: ${eq.level?.level || 'Unknown'} (${eq.percentage || 0}%)\n`;
    }
    content += `\nThank you for using ${APP_NAME}!\nContinue supporting your family's growth and development.\n`;
  }

  content += `

---
Generated by ${APP_NAME}
© ${new Date().getFullYear()} ${APP_NAME}
`;

  return content;
};

export const exportReport = async (reportData) => {
  try {
    const content = generateReportContent(reportData);
    const timestamp = Date.now();
    const fileName = `MindfulGuardian_Report_${timestamp}.txt`;

    const dir = FileSystem.documentDirectory;
    if (!dir) {
      return { success: false, error: 'Cannot access device storage.' };
    }

    const fileUri = dir + fileName;

    await FileSystem.writeAsStringAsync(fileUri, content, {
      encoding: FileSystem.EncodingType.UTF8,
    });

    const fileInfo = await FileSystem.getInfoAsync(fileUri);
    if (!fileInfo.exists) {
      return { success: false, error: 'Failed to create the report file.' };
    }

    const canShare = await Sharing.isAvailableAsync();
    if (!canShare) {
      // Sharing not available — show path so user can find the file
      return {
        success: false,
        error: `Sharing is not supported on this device.\nFile saved to: ${fileUri}`,
      };
    }

    await Sharing.shareAsync(fileUri, {
      mimeType: 'text/plain',
      dialogTitle: `Share Report — ${APP_NAME}`,
      UTI: 'public.plain-text',
    });

    return { success: true, fileUri };
  } catch (error) {
    console.error('Export error:', error);
    const msg = error?.message || 'Unknown error';
    // User cancelled the share dialog — not a real error
    if (
      msg.includes('cancel') ||
      msg.includes('Cancel') ||
      msg.includes('NSItemProviderErrorDomain')
    ) {
      return { success: true, cancelled: true };
    }
    return { success: false, error: msg };
  }
};
